/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/admin-api';
export * from './apis/issue-api';
export * from './apis/miscellaneous-api';
export * from './apis/notification-api';
export * from './apis/organization-api';
export * from './apis/repository-api';
export * from './apis/settings-api';
export * from './apis/user-api';

