/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * 
     * @type {number}
     * @memberof AccessToken
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    'sha1'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    'token_last_eight'?: string;
}

