/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * AddCollaboratorOption options when adding a user as a collaborator of a repository
 * @export
 * @interface AddCollaboratorOption
 */
export interface AddCollaboratorOption {
    /**
     * 
     * @type {string}
     * @memberof AddCollaboratorOption
     */
    'permission'?: string;
}

