/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * AnnotatedTagObject contains meta information of the tag object
 * @export
 * @interface AnnotatedTagObject
 */
export interface AnnotatedTagObject {
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTagObject
     */
    'sha'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTagObject
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTagObject
     */
    'url'?: string;
}

