/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CatalogStage a repo\'s catalog stage metadata
 * @export
 * @interface CatalogStage
 */
export interface CatalogStage {
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'branch_or_tag_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'contents_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'git_trees_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'release_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'released'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'tarball_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogStage
     */
    'zipball_url'?: string;
}

