/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CatalogVersionEndpoints Info on the versions of the catalog
 * @export
 * @interface CatalogVersionEndpoints
 */
export interface CatalogVersionEndpoints {
    /**
     * 
     * @type {string}
     * @memberof CatalogVersionEndpoints
     */
    'latest'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CatalogVersionEndpoints
     */
    'versions'?: { [key: string]: string; };
}

