/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Ingredient } from './ingredient';
// May contain unused imports in some cases
// @ts-ignore
import { Release } from './release';
// May contain unused imports in some cases
// @ts-ignore
import { Repository } from './repository';

/**
 * CatalogEntry represents a repository\'s metadata of a tag or default branch as an entry of the catalog
 * @export
 * @interface CatalogEntry
 */
export interface CatalogEntry {
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CatalogEntry
     */
    'alignment_counts'?: { [key: string]: number; };
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogEntry
     */
    'books'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'branch_or_tag_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'contents_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'git_trees_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof CatalogEntry
     */
    'id'?: number;
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof CatalogEntry
     */
    'ingredients'?: Array<Ingredient>;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'language_direction'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogEntry
     */
    'language_is_gl'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'language_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'metadata_api_contents_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'metadata_json_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'metadata_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'metadata_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'owner'?: string;
    /**
     * 
     * @type {Release}
     * @memberof CatalogEntry
     */
    'release'?: Release;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'released'?: string;
    /**
     * 
     * @type {Repository}
     * @memberof CatalogEntry
     */
    'repo'?: Repository;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'stage'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'tarbar_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntry
     */
    'zipball_url'?: string;
}

