/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CatalogStage } from './catalog-stage';

/**
 * CatalogStages a repo\'s catalog stages
 * @export
 * @interface CatalogStages
 */
export interface CatalogStages {
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    'draft'?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    'latest'?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    'preprod'?: CatalogStage;
    /**
     * 
     * @type {CatalogStage}
     * @memberof CatalogStages
     */
    'prod'?: CatalogStage;
}

