/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommitUser
 */
export interface CommitUser {
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitUser
     */
    'name'?: string;
}

