/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CommitDateOptions store dates for GIT_AUTHOR_DATE and GIT_COMMITTER_DATE
 * @export
 * @interface CommitDateOptions
 */
export interface CommitDateOptions {
    /**
     * 
     * @type {string}
     * @memberof CommitDateOptions
     */
    'author'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitDateOptions
     */
    'committer'?: string;
}

