/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateTeamOption options for creating a team
 * @export
 * @interface CreateTeamOption
 */
export interface CreateTeamOption {
    /**
     * 
     * @type {boolean}
     * @memberof CreateTeamOption
     */
    'can_create_org_repo'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamOption
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateTeamOption
     */
    'includes_all_repositories'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamOption
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTeamOption
     */
    'permission'?: CreateTeamOptionPermissionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateTeamOption
     */
    'units'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateTeamOption
     */
    'units_map'?: { [key: string]: string; };
}

export const CreateTeamOptionPermissionEnum = {
    Read: 'read',
    Write: 'write',
    Admin: 'admin'
} as const;

export type CreateTeamOptionPermissionEnum = typeof CreateTeamOptionPermissionEnum[keyof typeof CreateTeamOptionPermissionEnum];


