/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateLabelOption options for creating a label
 * @export
 * @interface CreateLabelOption
 */
export interface CreateLabelOption {
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    'color': string;
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateLabelOption
     */
    'name': string;
}

