/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateForkOption options for creating a fork
 * @export
 * @interface CreateForkOption
 */
export interface CreateForkOption {
    /**
     * name of the forked repository
     * @type {string}
     * @memberof CreateForkOption
     */
    'name'?: string;
    /**
     * organization name, if forking into an organization
     * @type {string}
     * @memberof CreateForkOption
     */
    'organization'?: string;
}

