/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreatePullRequestOption options when creating a pull request
 * @export
 * @interface CreatePullRequestOption
 */
export interface CreatePullRequestOption {
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'assignee'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreatePullRequestOption
     */
    'assignees'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'base'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'due_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'head'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreatePullRequestOption
     */
    'labels'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreatePullRequestOption
     */
    'milestone'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestOption
     */
    'title'?: string;
}

