/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateKeyOption options when creating a key
 * @export
 * @interface CreateKeyOption
 */
export interface CreateKeyOption {
    /**
     * An armored SSH key to add
     * @type {string}
     * @memberof CreateKeyOption
     */
    'key': string;
    /**
     * Describe if the key has only read access or read/write
     * @type {boolean}
     * @memberof CreateKeyOption
     */
    'read_only'?: boolean;
    /**
     * Title of the key to add
     * @type {string}
     * @memberof CreateKeyOption
     */
    'title': string;
}

