/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateGitRefOption options when creating a git ref in a repository
 * @export
 * @interface CreateGitRefOption
 */
export interface CreateGitRefOption {
    /**
     * The name of the reference.
     * @type {string}
     * @memberof CreateGitRefOption
     */
    'ref': string;
    /**
     * The target commitish for this reference.
     * @type {string}
     * @memberof CreateGitRefOption
     */
    'target': string;
}

