/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CreateGPGKeyOption options create user GPG key
 * @export
 * @interface CreateGPGKeyOption
 */
export interface CreateGPGKeyOption {
    /**
     * An armored GPG key to add
     * @type {string}
     * @memberof CreateGPGKeyOption
     */
    'armored_public_key': string;
    /**
     * 
     * @type {string}
     * @memberof CreateGPGKeyOption
     */
    'armored_signature'?: string;
}

