/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Repository } from './repository';

/**
 * DeployKey a deploy key
 * @export
 * @interface DeployKey
 */
export interface DeployKey {
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    'fingerprint'?: string;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    'key'?: string;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    'key_id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeployKey
     */
    'read_only'?: boolean;
    /**
     * 
     * @type {Repository}
     * @memberof DeployKey
     */
    'repository'?: Repository;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    'url'?: string;
}

