/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DismissPullReviewOptions are options to dismiss a pull review
 * @export
 * @interface DismissPullReviewOptions
 */
export interface DismissPullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof DismissPullReviewOptions
     */
    'message'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DismissPullReviewOptions
     */
    'priors'?: boolean;
}

