/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditLabelOption options for editing a label
 * @export
 * @interface EditLabelOption
 */
export interface EditLabelOption {
    /**
     * 
     * @type {string}
     * @memberof EditLabelOption
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditLabelOption
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditLabelOption
     */
    'name'?: string;
}

