/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditGitHookOption options when modifying one Git hook
 * @export
 * @interface EditGitHookOption
 */
export interface EditGitHookOption {
    /**
     * 
     * @type {string}
     * @memberof EditGitHookOption
     */
    'content'?: string;
}

