/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditReactionOption contain the reaction type
 * @export
 * @interface EditReactionOption
 */
export interface EditReactionOption {
    /**
     * 
     * @type {string}
     * @memberof EditReactionOption
     */
    'content'?: string;
}

