/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EditHookOption options when modify one hook
 * @export
 * @interface EditHookOption
 */
export interface EditHookOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditHookOption
     */
    'active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditHookOption
     */
    'branch_filter'?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EditHookOption
     */
    'config'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof EditHookOption
     */
    'events'?: Array<string>;
}

