/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Email an email address belonging to a user
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    'email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Email
     */
    'primary'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Email
     */
    'verified'?: boolean;
}

