/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FileCommitResponse } from './file-commit-response';
// May contain unused imports in some cases
// @ts-ignore
import { PayloadCommitVerification } from './payload-commit-verification';

/**
 * FileDeleteResponse contains information about a repo\'s file that was deleted
 * @export
 * @interface FileDeleteResponse
 */
export interface FileDeleteResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FileDeleteResponse
     */
    'commit'?: FileCommitResponse;
    /**
     * 
     * @type {object}
     * @memberof FileDeleteResponse
     */
    'content'?: object;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FileDeleteResponse
     */
    'verification'?: PayloadCommitVerification;
}

