/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GeneralAttachmentSettings contains global Attachment settings exposed by API
 * @export
 * @interface GeneralAttachmentSettings
 */
export interface GeneralAttachmentSettings {
    /**
     * 
     * @type {string}
     * @memberof GeneralAttachmentSettings
     */
    'allowed_types'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralAttachmentSettings
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    'max_files'?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    'max_size'?: number;
}

