/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GeneralUISettings contains global ui settings exposed by API
 * @export
 * @interface GeneralUISettings
 */
export interface GeneralUISettings {
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneralUISettings
     */
    'allowed_reactions'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeneralUISettings
     */
    'custom_emojis'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GeneralUISettings
     */
    'default_theme'?: string;
}

