/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GitBlobResponse represents a git blob
 * @export
 * @interface GitBlobResponse
 */
export interface GitBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    'encoding'?: string;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    'sha'?: string;
    /**
     * 
     * @type {number}
     * @memberof GitBlobResponse
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof GitBlobResponse
     */
    'url'?: string;
}

