/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GitObject
 */
export interface GitObject {
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    'sha'?: string;
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GitObject
     */
    'url'?: string;
}

