/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GitEntry } from './git-entry';

/**
 * GitTreeResponse returns a git tree
 * @export
 * @interface GitTreeResponse
 */
export interface GitTreeResponse {
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    'page'?: number;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    'sha'?: string;
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    'total_count'?: number;
    /**
     * 
     * @type {Array<GitEntry>}
     * @memberof GitTreeResponse
     */
    'tree'?: Array<GitEntry>;
    /**
     * 
     * @type {boolean}
     * @memberof GitTreeResponse
     */
    'truncated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    'url'?: string;
}

