/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GPGKeyEmail an email attached to a GPGKey
 * @export
 * @interface GPGKeyEmail
 */
export interface GPGKeyEmail {
    /**
     * 
     * @type {string}
     * @memberof GPGKeyEmail
     */
    'email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKeyEmail
     */
    'verified'?: boolean;
}

