/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IssueTemplate represents an issue template for a repository
 * @export
 * @interface IssueTemplate
 */
export interface IssueTemplate {
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'about'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'file_name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssueTemplate
     */
    'labels'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    'title'?: string;
}

