/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MergePullRequestForm form for merging Pull Request
 * @export
 * @interface MergePullRequestOption
 */
export interface MergePullRequestOption {
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    'Do': MergePullRequestOptionDoEnum;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    'MergeCommitID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    'MergeMessageField'?: string;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    'MergeTitleField'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MergePullRequestOption
     */
    'delete_branch_after_merge'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MergePullRequestOption
     */
    'force_merge'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    'head_commit_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MergePullRequestOption
     */
    'merge_when_checks_succeed'?: boolean;
}

export const MergePullRequestOptionDoEnum = {
    Merge: 'merge',
    Rebase: 'rebase',
    RebaseMerge: 'rebase-merge',
    Squash: 'squash',
    ManuallyMerged: 'manually-merged'
} as const;

export type MergePullRequestOptionDoEnum = typeof MergePullRequestOptionDoEnum[keyof typeof MergePullRequestOptionDoEnum];


