/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * MigrateRepoForm form for migrating repository this is used to interact with web ui
 * @export
 * @interface MigrateRepoForm
 */
export interface MigrateRepoForm {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'auth_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'auth_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'auth_username'?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'clone_addr': string;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'issues'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'labels'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'lfs'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'lfs_endpoint'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'milestones'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'mirror'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'mirror_interval'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'private'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'pull_requests'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'releases'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    'repo_name': string;
    /**
     * GitServiceType represents a git service
     * @type {number}
     * @memberof MigrateRepoForm
     */
    'service'?: number;
    /**
     * 
     * @type {number}
     * @memberof MigrateRepoForm
     */
    'uid': number;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    'wiki'?: boolean;
}

