/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * NodeInfoSoftware contains Metadata about server software in use
 * @export
 * @interface NodeInfoSoftware
 */
export interface NodeInfoSoftware {
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    'homepage'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    'repository'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInfoSoftware
     */
    'version'?: string;
}

