/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * NotificationCount number of unread notifications
 * @export
 * @interface NotificationCount
 */
export interface NotificationCount {
    /**
     * 
     * @type {number}
     * @memberof NotificationCount
     */
    'new'?: number;
}

