/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * OrganizationPermissions list different users permissions on an organization
 * @export
 * @interface OrganizationPermissions
 */
export interface OrganizationPermissions {
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_create_repository'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_read'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'can_write'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'is_admin'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationPermissions
     */
    'is_owner'?: boolean;
}

