/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * PackageFile represents a package file
 * @export
 * @interface PackageFile
 */
export interface PackageFile {
    /**
     * 
     * @type {number}
     * @memberof PackageFile
     */
    'Size'?: number;
    /**
     * 
     * @type {number}
     * @memberof PackageFile
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PackageFile
     */
    'md5'?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageFile
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageFile
     */
    'sha1'?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageFile
     */
    'sha256'?: string;
    /**
     * 
     * @type {string}
     * @memberof PackageFile
     */
    'sha512'?: string;
}

