/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * PublicKey publickey is a user key to push code to repository
 * @export
 * @interface PublicKey
 */
export interface PublicKey {
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'fingerprint'?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicKey
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'key_type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicKey
     */
    'read_only'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    'url'?: string;
    /**
     * 
     * @type {User}
     * @memberof PublicKey
     */
    'user'?: User;
}

