/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Team } from './team';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * PullReview represents a pull request review
 * @export
 * @interface PullReview
 */
export interface PullReview {
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    'body'?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    'comments_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    'commit_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    'dismissed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    'official'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    'pull_request_url'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    'stale'?: boolean;
    /**
     * ReviewStateType review state type
     * @type {string}
     * @memberof PullReview
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    'submitted_at'?: string;
    /**
     * 
     * @type {Team}
     * @memberof PullReview
     */
    'team'?: Team;
    /**
     * 
     * @type {User}
     * @memberof PullReview
     */
    'user'?: User;
}

