/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GitObject } from './git-object';

/**
 * 
 * @export
 * @interface Reference
 */
export interface Reference {
    /**
     * 
     * @type {GitObject}
     * @memberof Reference
     */
    'object'?: GitObject;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    'ref'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reference
     */
    'url'?: string;
}

