/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Attachment } from './attachment';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * Release represents a repository release
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof Release
     */
    'assets'?: Array<Attachment>;
    /**
     * 
     * @type {User}
     * @memberof Release
     */
    'author'?: User;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    'draft'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'html_url'?: string;
    /**
     * 
     * @type {number}
     * @memberof Release
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    'prerelease'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'published_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'tag_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'tarball_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'target_commitish'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    'zipball_url'?: string;
}

