/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * StopWatch represent a running stopwatch
 * @export
 * @interface StopWatch
 */
export interface StopWatch {
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'duration'?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    'issue_index'?: number;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'issue_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'repo_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    'repo_owner_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    'seconds'?: number;
}

