/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SubmitPullReviewOptions are options to submit a pending pull review
 * @export
 * @interface SubmitPullReviewOptions
 */
export interface SubmitPullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof SubmitPullReviewOptions
     */
    'body'?: string;
    /**
     * ReviewStateType review state type
     * @type {string}
     * @memberof SubmitPullReviewOptions
     */
    'event'?: string;
}

