/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Team } from './team';

/**
 * 
 * @export
 * @interface TeamSearch200Response
 */
export interface TeamSearch200Response {
    /**
     * 
     * @type {Array<Team>}
     * @memberof TeamSearch200Response
     */
    'data'?: Array<Team>;
    /**
     * 
     * @type {boolean}
     * @memberof TeamSearch200Response
     */
    'ok'?: boolean;
}

