/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+1682-g5f768e5ff
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TopicResponse for returning topics
 * @export
 * @interface TopicResponse
 */
export interface TopicResponse {
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    'created'?: string;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    'repo_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    'topic_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    'updated'?: string;
}

