/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.3+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TopicName a list of repo topic names
 * @export
 * @interface TopicName
 */
export interface TopicName {
    /**
     * 
     * @type {Array<string>}
     * @memberof TopicName
     */
    'topics'?: Array<string>;
}

