/* tslint:disable */
/* eslint-disable */
/**
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * The version of the OpenAPI document: 1.17.4+dcs
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WikiCommit } from './wiki-commit';

/**
 * WikiPageMetaData wiki page meta information
 * @export
 * @interface WikiPageMetaData
 */
export interface WikiPageMetaData {
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    'html_url'?: string;
    /**
     * 
     * @type {WikiCommit}
     * @memberof WikiPageMetaData
     */
    'last_commit'?: WikiCommit;
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    'sub_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof WikiPageMetaData
     */
    'title'?: string;
}

